### ISSUE TITLE
can you provide a small dataset for research purpose?

### ISSUE THREAD

**Issue by SeekPoint** [guykush/TermSetExpansion-MPB#1]
the original dataset are too big to download

**Comment by guykush** [comment]
I guess you are talking about the corpus (text files) and not the set files which are pretty small: these text files are just a dump of Wikipedia where every article is turned into a text file. You can download the Wikipedia dump (see README for link), and generate text files from the dump (using the makeTextFiles python script. also in README) only from some of the articles, depending on the corpus size you want. You can then index these text files using the index_text_files python script.

**Comment by SeekPoint** [comment]
sure, got it
