### ISSUE TITLE
can we use it in east Asia language like Chinese, japanese etc without word segmentation?

### ISSUE THREAD

**Issue by SeekPoint** [guykush/TermSetExpansion-MPB#2]

**Comment by guykush** [comment]
I haven't tried this, my guess would be you could if you have an MLM trained on this language (and you will probably need some code modifications)

**Comment by SeekPoint** [comment]
MLM
---do you means some pre-trained language model like BERT. XNET, right?

**Comment by guykush** [comment]
yep, Masked Language Model.
